# Generated by Django 5.0.6 on 2024-07-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='room',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceType',
        ),
        migrations.AddField(
            model_name='bill',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation'),
        ),
        migrations.AddField(
            model_name='bill',
            name='services',
            field=models.ManyToManyField(to='hotel.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='nameService',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
