# Generated by Django 5.0.6 on 2024-07-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_service_reservation_remove_service_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ManyToManyField(related_name='rooms', to='hotel.room'),
        ),
    ]
