# Generated by Django 5.0.6 on 2024-07-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_reservation_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
