# Generated by Django 5.0.6 on 2024-07-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_reservation_statuscheckin_reservationservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='services',
        ),
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(null=True, through='hotel.ReservationService', to='hotel.service'),
        ),
    ]
