# Generated by Django 5.0.6 on 2024-07-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_bill_services_reservation_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationservice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
