# Generated by Django 5.0.6 on 2024-07-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_reservationservice_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationservice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
