# Generated by Django 5.0.6 on 2024-07-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_reservationservice_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(through='hotel.ReservationService', to='hotel.service'),
        ),
    ]
