# Generated by Django 5.0.6 on 2024-07-27 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_reservation_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='reservation',
        ),
        migrations.AddField(
            model_name='bill',
            name='reservation_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reservationservice'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='totalAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
