# Generated by Django 5.0.6 on 2024-07-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_remove_bill_reservation_bill_reservation_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='guest',
        ),
    ]
