# Generated by Django 5.0.6 on 2024-07-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_bill_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='summary',
        ),
    ]
