# Generated by Django 5.0.6 on 2024-07-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_roomtype_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='reservation_service',
        ),
        migrations.AddField(
            model_name='bill',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation'),
        ),
    ]
